<a href="https://colab.research.google.com/github/Wnjoki/Data-Science-Exercises/blob/main/Convolution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
# Define the grayscale image I of dimension 5x5 
I = np.array([
    [13, 10, 15, 12, 8],
    [9, 11, 10, 5, 6],
    [45, 21, 16, 74, 50],
    [11, 33, 24, 48, 5],
    [61, 71, 82, 45, 3]
])

#Define the sobel-filter Gx and Gx 

Gx = np.array([ 
    [1, 0, -1],
    [2, 0, -2],
    [1, 0, -1]
])

 

Gy = np.array([
    [1, 2, 1],
    [0, 0, 0],
    [-1, -2, -1]
])



In [4]:
#perform the convolution with Gx and Gy
from scipy.signal import convolve2d

Ix = convolve2d(I, Gx, mode='valid')
Iy = convolve2d(I, Gy, mode='valid')


In [5]:
# Perform max pooling 
pooling_size = 2
stride = 1

pooled_Ix = np.zeros((3, 3))
pooled_Iy = np.zeros((3, 3))

for i in range(0, Ix.shape[0] - pooling_size + 1, stride):
    for j in range(0, Ix.shape[1] - pooling_size + 1, stride):
        pooled_Ix[i//stride, j//stride] = np.max(Ix[i:i+pooling_size, j:j+pooling_size])
        pooled_Iy[i//stride, j//stride] = np.max(Iy[i:i+pooling_size, j:j+pooling_size])


In [6]:

# Print the results
print("Grayscale Image I:\n", I)
print("\nIx (After Sobel filter and convolution):\n", Ix)
print("\nIy (After Sobel filter and convolution):\n", Iy)
print("\nPooled Ix:\n", pooled_Ix)
print("\nPooled Iy:\n", pooled_Iy)

Grayscale Image I:
 [[13 10 15 12  8]
 [ 9 11 10  5  6]
 [45 21 16 74 50]
 [11 33 24 48  5]
 [61 71 82 45  3]]

Ix (After Sobel filter and convolution):
 [[-25  43  19]
 [-44 115  45]
 [ 18  57 -83]]

Iy (After Sobel filter and convolution):
 [[ 55  75 167]
 [ 60  93  99]
 [182 153 -39]]

Pooled Ix:
 [[115. 115.   0.]
 [115. 115.   0.]
 [  0.   0.   0.]]

Pooled Iy:
 [[ 93. 167.   0.]
 [182. 153.   0.]
 [  0.   0.   0.]]
